import type { PlatformName } from '../entities/ITransaction';
import type { Result } from '../shared/Result';

export interface OAuthPlatformConfig {
  readonly platform: PlatformName;
  readonly clientId: string;
  readonly clientSecret: string;
  readonly scopes: readonly string[];
  readonly authorizationUrl: string;
  readonly tokenUrl: string;
  readonly redirectUri: string;
}

/**
 * Normalized token set returned after a successful OAuth exchange or refresh.
 * `raw` is the opaque platform response retained for debugging.
 */
export interface OAuthTokenSet {
  readonly accessToken: string;
  readonly refreshToken?: string;
  readonly expiresAt: string; // ISO-8601
  readonly scopes: readonly string[];
  readonly raw: Record<string, unknown>;
}

export interface OAuthCallbackParams {
  readonly code: string;
  readonly state: string;
  readonly error?: string;
  readonly errorDescription?: string;
}

export type OAuthErrorCode =
  | 'INVALID_STATE'
  | 'TOKEN_EXCHANGE_FAILED'
  | 'REFRESH_FAILED'
  | 'PROVIDER_ERROR'
  | 'UNSUPPORTED_PLATFORM'
  | 'UNKNOWN';

export interface OAuthError {
  readonly code: OAuthErrorCode;
  readonly message: string;
  readonly retryable: boolean;
  readonly details?: Record<string, unknown>;
}

/**
 * Port for OAuth 2.0 Authorization Code flow per platform.
 * Concrete strategies live in infrastructure; application layer depends only on this port (DIP).
 */
export interface IOAuthService {
  readonly platform: PlatformName;

  /**
   * Builds the platform authorization URL.
   * `state` is a caller-supplied CSRF token (generated by OAuthOrchestrator).
   */
  buildAuthorizationUrl(state: string): Result<{ url: string; state: string }, OAuthError>;

  /**
   * Exchanges an authorization code for an access/refresh token pair.
   */
  exchangeCodeForTokens(params: OAuthCallbackParams): Promise<Result<OAuthTokenSet, OAuthError>>;

  /**
   * Refreshes an expired access token using the stored refresh token.
   */
  refreshAccessToken(refreshToken: string): Promise<Result<OAuthTokenSet, OAuthError>>;
}
